@file:Suppress("OPT_IN_USAGE")

package naksha.auth.check

import naksha.base.*
import naksha.base.Platform.Platform_C.forKClass
import naksha.base.PlatformMapApi.PlatformMapApi_C.map_get
import kotlin.js.JsExport
import kotlin.js.JsName
import kotlin.js.JsStatic
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

/**
 * The base class of all checks, checks are a tests of operation parameter values.
 *
 * If being extended, the extending class need to be registered with [CheckOp] enumeration, and must implement the [test] method.
 *
 * This base class is returned for unknown checks, and will [test] all values provided in [anyOf] _(via logical OR)_ and [allOf] _(via logical AND)_. The default [test] implementation always just returns _false_ when being invoked, but the default implementation allow child-checks. This allows simplified _**and**_ / _**or**_ checks, like:
 * ```js
 * {anyOf:[
 *   {op:"eq", anyOf:["a","b"]},
 *   {op:"startsWith", allOf:["foo"], ignoreCase:true}
 * ]}
 * ```
 * Because there is no `op` in the outer object, it will be parsed into a simple [Check], which will tests all [anyOf] child-checks. Therefore, the check is true, when the parameter value is either `a` or `b`, or is a string that starts with `foo`, ignoring case _(so `FooBar` matches as well)_.
 *
 * As this is root implementation, all checks may optionally [support child-checks][supportChildChecks], for example:
 * ```js
 * {op:"eq", anyOf:[
 *   "a",
 *   "b",
 *   {op:"startsWith", allOf:["foo"], ignoreCase:true}
 * ]}
 * ```
 * This would do the same as above, if the [Equals] check would support child-checks, just written differently. Therefore, all checks can potentially support child-check execution. Beware that [Equals] does not support child-checks!
 *
 * **Note**: These checks are normally generated by UPM _(User Permission Management)_, therefore this is only relevant for implementors of new checks or services.
 * @since 3.0
 * @see CheckOp
 * @see naksha.auth.ServiceOpParams
 */
@JsExport
open class Check() : AnyObject() {

    @JsName("CheckOf")
    constructor(op: String): this() {
        set("op", op)
    }

    companion object Check_C {
        /**
         * The [PlatformType] of [Check].
         * @since 3.0
         */
        @JvmField
        @JsStatic
        val TYPE: PlatformType<Check> = forKClass(Check::class).withPackageName(PACKAGE_NAME)

        /**
         * Returns the [check] for the given value.
         *
         * The given value is expected to be [any object][AnyObject] with the following JSON format:
         * ```js
         * {op:"eq",anyOf:[12]}
         * ```
         * This is normally part of a [UserRightsFilter][naksha.auth.UserRightsFilter]. However, there are a few exceptions, if the value is no object, but it is:
         * - a `String` and the first and last character are a star _(`*`)_, returns an [Contains]
         * - a `String` and the first character is a star _(`*`)_, returns an [StartsWith]
         * - a `String` and the last character is a star _(`*`)_, returns an [EndsWith]
         * - a `String` that starts and ends with slash _(`/`)_, optionally ends with '/i' to turn on case-insensitive, returns an [Matches]
         * - a `List<Scalar>`, then all values are required to be a scalar _(otherwise it's ignored)_, and then converted into child-checks, added into a plain [Check] with the child-checks in [anyOf].
         * - is any other `Scalar`, returns an [Equals] with [anyOf].
         *
         * @param value The raw value as read from [UserRightsFilter][naksha.auth.UserRightsFilter] via `getRaw(operationName)`.
         * @return either the given object cast to the correct [Check] operation, or the given value converted into a valid [Check] operation; eventually, when nothing else is possible, a blank [Check], that always fails.
         * @since 3.0
         */
        @JvmStatic
        @JsStatic
        fun forAny(value: Any?): Check = when (value) {
            is Check -> value
            is PlatformMap -> {
                val raw = map_get(value, "op")
                val op = CheckOp.of(raw)
                op.checkType.proxy(value)
            }
            is MapProxy<*, *> -> {
                val raw = value["op"]
                val op = CheckOp.of(raw)
                op.checkType.proxy(value)
            }
            is List<*>, is PlatformList -> {
                val _value: List<*> = if (value is PlatformList) AnyList.TYPE.proxy(value) else value as List<*>
                var toEquals = true
                for (v in _value) {
                    if (v is String && (
                        v.startsWith('*') || v.endsWith('*') ||
                        (v.startsWith('/') && (v.endsWith('/') || v.endsWith("/i")))
                    )) {
                        toEquals = false
                        break
                    }
                }
                if (toEquals) {
                    val eq = Equals()
                    val list = eq.useAnyOf()
                    for (v in _value) {
                        when (v) {
                            is String -> list.add(v)
                            is Boolean -> list.add(v)
                            is Byte -> list.add(v.toInt())
                            is Short -> list.add(v.toInt())
                            is Int -> list.add(v)
                            is Long -> list.add(v.toInt64())
                            is Int64 -> list.add(v)
                            is Float -> list.add(v.toDouble())
                            is Double -> list.add(v)
                        }
                    }
                    eq
                } else {
                    val or = Check()
                    val list = or.useAnyOf()
                    for (v in _value) {
                        list.add(forAny(v))
                    }
                    or
                }
            }
            else -> forScalar(value)
        }

        private fun forScalar(value: Any?): Check = when (value) {
            is Check -> value
            is String -> {
                if (value.startsWith('*') && value.endsWith('*')) Contains(value.substring(0, value.length - 1))
                else if (value.startsWith('*')) EndsWith(value.substring(1))
                else if (value.endsWith('*')) StartsWith(value.substring(0, value.length - 1))
                else if (value.startsWith('/') && value.endsWith('/')) Matches(value.substring(1, value.length - 1))
                else if (value.startsWith('/') && value.endsWith("/i")) Matches(value.substring(1, value.length - 1)).withIgnoreCase(true)
                else Equals(value)
            }
            is Boolean -> Equals(value)
            is Byte -> Equals(value.toInt())
            is Short -> Equals(value.toInt())
            is Int -> Equals(value)
            is Long -> Equals(value.toInt64())
            is Int64 -> Equals(value)
            is Float -> Equals(value.toDouble())
            is Double -> Equals(value)
            else -> Check()
        }

        private val BOOLEAN_MEMBER = NotNullProperty<Check, Boolean>(Boolean_TYPE) { _, _ -> false }
        private val STRING_MEMBER = NullableProperty<Check, String>(String_TYPE)
        private val OP_CODE_MEMBER = NotNullEnum<Check, CheckOp>(CheckOp.TYPE) { _,_ -> CheckOp.UNDEFINED }
        private val ANY_LIST_MEMBER = NullableProperty<Check, AnyList>(AnyList.TYPE)
    }

    /**
     * The opcode of the check to execute.
     * @since 3.0
     */
    val op: CheckOp by OP_CODE_MEMBER

    /**
     * Iterate all values from this list.
     *
     * If [supportChildChecks] is _true_ and the value is a `Map<*,*>`, cast the value to `Check`, and execute this child-check against the parameter _(`child.matches(parameter)`)_. Otherwise, execute the [test] with the value against the parameter _(`this.test(parameter, value)`)_.
     *
     * The check is successful ones the first test or child-check is successful. When all tests or child-checks fail, the check fails as well.
     * @since 3.0
     * @see test
     */
    var anyOf: AnyList? by ANY_LIST_MEMBER

    fun useAnyOf(): AnyList {
        var list = anyOf
        if (list == null) {
            list = AnyList()
            anyOf = list
        }
        return list
    }

    open fun withAnyOf(vararg any: Any?): Check {
        this.anyOf = AnyList().appendAll(*any)
        return this
    }

    /**
     * Iterate all values from this list.
     *
     * If [supportChildChecks] is _true_ and the value is a `Map<*,*>`, cast the value to `Check`, and execute this child-check against the parameter _(`child.matches(parameter)`)_. Otherwise, execute the [test] with the value against the parameter _(`this.test(parameter, value)`)_.
     *
     * The check is successful if all tests or child-checks are successful. Ones the first test or child-check failed, the check fails as well.
     * @since 3.0
     * @see test
     */
    var allOf: AnyList? by ANY_LIST_MEMBER

    fun useAllOf(): AnyList {
        var list = allOf
        if (list == null) {
            list = AnyList()
            allOf = list
        }
        return list
    }

    open fun withAllOf(vararg any: Any?): Check {
        this.allOf = AnyList().appendAll(*any)
        return this
    }

    /**
     * If explicitly set to `true`, then the check should ignore string casing, forces the test to be string based.
     * @since 3.0
     */
    var ignoreCase: Boolean by BOOLEAN_MEMBER

    open fun withIgnoreCase(ignore: Boolean): Check {
        this.ignoreCase = ignore
        return this
    }

    /**
     * If not `null`, the check expects that parameter is a `Map<String.*>` and the [test] is applied against the value assigned to the defined `key`.
     * @since 3.0
     */
    var key: String? by STRING_MEMBER

    /**
     * This method is called by the default [matches] implementation to test if child-checks should be supported.
     * @return _true_ if this check wants to support child-checks; _false_ otherwise.
     */
    protected open fun supportChildChecks(): Boolean = true

    /**
     * Tests if the given operation parameter fulfills the check condition, optionally considering child-checks.
     *
     * @param parameter The operation parameter to test.
     * @return _true_ if the given parameter matches; _false_ otherwise.
     * @since 3.0
     */
    fun matches(parameter: Any?): Boolean {
        var param = parameter
        if (key != null) {
            if (parameter !is Map<*,*>) return false
            if (!parameter.containsKey(key)) return false
            param = parameter[key]
        }
        val supportChildChecks = supportChildChecks()
        var ok = false
        val anyOf = this.anyOf
        if (!anyOf.isNullOrEmpty()) {
            for (value in anyOf) {
                if (supportChildChecks && value is MapProxy<*, *>) {
                    // Child-check !
                    val childCheck = forAny(value)
                    if (childCheck.matches(param)) {
                        ok = true
                        break
                    }
                } else if (test(param, value)) {
                    ok = true
                    break
                }
            }
            if (!ok) return false
        }
        val allOf = this.allOf
        if (!allOf.isNullOrEmpty()) {
            ok = true
            for (value in allOf) {
                if (supportChildChecks && value is MapProxy<*, *>) {
                    // Child-check !
                    val childCheck = forAny(value)
                    if (!childCheck.matches(param)) {
                        ok = false
                        break
                    }
                } else if (!test(param, value)) {
                    ok = false
                    break
                }
            }
        }
        return ok
    }

    /**
     * Tests if the given operation parameter fulfills the check condition against the given value.
     *
     * @param parameter The operation parameter to test.
     * @param value The value against which to test, must be a `Map<String, Scalar>`, `List<Scalar>` or `Scalar` _(null, boolean, string, int, int64 or double)_.
     * @return _true_ if the given parameter matches the given value; _false_ otherwise.
     * @since 3.0
     */
    protected open fun test(parameter: Any?, value: Any?): Boolean = false
}