curations:
  license_findings:
    - path: "here-naksha-lib-core/src/main/java/com/here/naksha/lib/core/models/License.java"
      start_lines: "56"
      line_count: 1
      detected_license: "OSL-3.0"
      reason: "CODE"
      comment: "The scanner matches an enumerator `OSL-3.0`."
      concluded_license: "NONE"
    - path: "here-naksha-lib-core/src/main/java/com/here/naksha/lib/core/models/License.java"
      start_lines: "62"
      line_count: 1
      detected_license: "ODbL-1.0"
      reason: "CODE"
      comment: "The scanner matches an enumerator `ODbL-1.0`."
      concluded_license: "NONE"
excludes:
  #paths:
  #- pattern: "**/src/test/**"
  #  reason: "TEST_TOOL_OF"
  #  comment: "This directory only contains tests to verify correct functioning of XYZ Hub. Not included in released artifacts."
  scopes:
  - pattern: "provided"
    reason: "PROVIDED_DEPENDENCY_OF"
    comment: "Scope with dependencies provided by the JDK or container at runtime. Not included in released artifacts."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for testing. Not included in released artifacts."
