curations:
  license_findings:
    - path: "here-naksha-lib-core/src/main/java/**/License.java"
      reason: "INCORRECT"
      comment: "The file contains all possible license identifiers for the content of a space."
      concluded_license: "Apache-2.0"
excludes:
  #paths:
  #- pattern: "**/src/test/**"
  #  reason: "TEST_TOOL_OF"
  #  comment: "This directory only contains tests to verify correct functioning of XYZ Hub. Not included in released artifacts."
  scopes:
  - pattern: "provided"
    reason: "PROVIDED_DEPENDENCY_OF"
    comment: "Scope with dependencies provided by the JDK or container at runtime. Not included in released artifacts."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for testing. Not included in released artifacts."
