# You should place a gradle.properties file in your home directory with the correct values
# Git project URI (used as pom metadata for publication)
projectRepoURI=github.com/heremaps/naksha

# In Linux: ~/.gradle/gradle.properties
# If publishing to maven central, use: https://mvnrepository.com/artifact/io.github.naksha-oss/
mavenUrl=some_maven_repo_publish_url
mavenUser=YourUserName
mavenPassword=YourPassword

# When updating the version, please consider:
# automatically updated:
#   here-naksha-lib-core/NakshaVersion (static property: latest)
# manually update:
#   here-naksha-app-service/src/main/resources/swagger/openapi.yaml (info.version property)
#   here-naksha-lib-psql/src/commonMain/kotlin/naksha/psql/LibPsql.kt (adminVersion property)
#     Warning: Only update LibPsql version, if there is a change in SQL functions!
#              The reason is, that this version is encoded in the database, and when updated, forced an upgrade!
version=3.0.0-beta.29

org.gradle.jvmargs=-Xmx12g
kotlin.code.style=official
kotlin.jvm.enableDefaultMethods=true

# `whole-program` = The Kotlin/JS compiler could generate a single .js file for the whole project.
# `per-module` = separate .js file for each project module.
# `per-file` = one (or two, if the file contains exported declarations) JavaScript file per each Kotlin file.
#kotlin.js.ir.output.granularity=per-file

# Output build reports in JSON in the given directory
# kotlin.build.report.output=json
# kotlin.build.report.json.directory="my/directory/path"
