@file:Suppress("OPT_IN_USAGE", "MemberVisibilityCanBePrivate")

package naksha.model.request

import naksha.base.AnyObjectList
import naksha.base.Int64
import naksha.base.TupleNumber
import naksha.model.*
import naksha.model.objects.NakshaCollection
import kotlin.js.JsExport
import kotlin.jvm.JvmField

/**
 * A result-set as generated by the storage, and returned for a [ReadRequest] or [ReadHandle] request, being returned as part of a [SuccessResponse].
 *
 * Beware that the result-set is an optional object, not all storages will support result-sets. If they do not support them, they will directly just return the objects.
 *
 * Even when the storage supports result-sets, there are two kind of result-sets. Those with tuple-support and those without, see [supportTuple].
 *
 * If a result-set is given, [tuple-numbers][TupleNumber] are always available, but they may not be used to load [Tuple], when the storage does not support tuple.
 * @since 3.0
 */
@JsExport
abstract class ResultSet(
    /**
     * The request for which this result was produced _(informational purpose only)_.
     * @since 3.0
     */
    @JvmField
    val request: Request,

    /**
     * The storage that produced the result-set.
     * @since 3.0
     */
    @JvmField
    val storage: IStorage,

    /**
     * The session that was used to produce the result-set.
     *
     * ### Warning
     * The session may have been closed already! If that is the case, loading results may fail.
     * @since 3.0
     */
    @JvmField
    val session: ISession,

    /**
     * The size of the result-set, so the number of objects contained in the result-set.
     * @since 3.0
     */
    @JvmField
    val size: Int,
) {
    /**
     * The offset of the first object in this result-set; if the storage knows the offset of this result-set in the total results. The property will be `null` if the storage does not have this information.
     *
     * If the storage provides this information, can be used to calculate page numbers.
     * @since 3.0
     */
    abstract val offset: Int?

    /**
     * The total amount of results generated for the original query, `null` if the storage does not know the total amount of results.
     *
     * If the storage provides this information, can be used to calculate page numbers.
     * @since 3.0
     */
    abstract val totalSize: Long?

   /**
     * If a handle was requested and there are more results in the result-set, the handle to the next results.
     * @since 3.0
     */
    abstract val handle: ByteArray?

    /**
     * If the storage supports tuple.
     * @since 3.0
     */
    abstract val supportTuple: Boolean

    /**
     * Returns a single feature-number from the result set.
     * @param i the index in the result-set to query.
     * @return the feature-number.
     * @since 3.0
     * @throws naksha.base.NakshaException with error [ILLEGAL_STATE][naksha.base.NakshaError.ILLEGAL_STATE] if the index is out of bounds or the session to which this result-set is linked was closed.
     */
    abstract fun getFeatureNumber(i: Int): Long

    /**
     * Returns the version from the result set.
     * @param i the index in the result-set to query.
     * @return the version.
     * @since 3.0
     * @throws naksha.base.NakshaException with error [ILLEGAL_STATE][naksha.base.NakshaError.ILLEGAL_STATE] if the index is out of bounds or the session to which this result-set is linked was closed.
     */
    abstract fun getVersion(i: Int): Long

    /**
     * Returns the tuple-number from the result set.
     * @param i the index in the result-set to query.
     * @return the version.
     * @since 3.0
     * @throws naksha.base.NakshaException with error [ILLEGAL_STATE][naksha.base.NakshaError.ILLEGAL_STATE] if the index is out of bounds or the session to which this result-set is linked was closed.
     */
    abstract fun getTupleNumber(i: Int): TupleNumber

    /**
     * Returns the tuple-number in the given range from the result set. The result can be used as direct input into [ISession.loadTuples].
     *
     *
     * @param from the index of the first tuple-number to include.
     * @param to the index of the first tuple-number to exclude.
     * @return the tuple-number in the given range.
     * @since 3.0
     * @throws naksha.base.NakshaException with error [ILLEGAL_ARGUMENT][naksha.base.NakshaError.ILLEGAL_ARGUMENT] if the index is out of bounds or [ILLEGAL_STATE][naksha.base.NakshaError.ILLEGAL_STATE], if the session to which this result-set is linked was closed.
     */
    abstract fun getTupleNumbers(from: Int = 0, to:Int = size): ITupleNumberArray

    /**
     * Serializes the result-set in the given range.
     *
     * Dependent on the implementation contains either only the [TupleNumber] or the full results in serialized form.
     *
     * @param from the index of the first object to include.
     * @param to the index of the first object to exclude.
     * @return the objects in the given range serialized.
     * @since 3.0
     * @throws naksha.base.NakshaException with error [ILLEGAL_ARGUMENT][naksha.base.NakshaError.ILLEGAL_ARGUMENT] if the index is out of bounds or [ILLEGAL_STATE][naksha.base.NakshaError.ILLEGAL_STATE], if the session to which this result-set is linked was closed.
     * @see ISession.restoreResultSet
     */
    abstract fun getBytes(from: Int = 0, to: Int = size): ByteArray

    /**
     * Returns the objects in the given range from the result-set.
     *
     * If the storage supports [Tuple], then it will first load the tuple and apply the tuple-filter. Some implementation will skip the tuple loading, as they do not support tuple. The final run always executed is the decoding into objects, applying the [object-filter][IObjectFilter].
     *
     * @param from the index of the first object to include.
     * @param to the index of the first object to exclude.
     * @param limit if the client is not interested in more than the given amount of features, the limit needed after filtering.
     * @param tupleFilter a tuple-filter to be executed before the object-filter.
     * @param objectFilter an object-filter to be executed to filter the results.
     * @return the objects in the given range.
     * @since 3.0
     * @throws naksha.base.NakshaException with error [ILLEGAL_ARGUMENT][naksha.base.NakshaError.ILLEGAL_ARGUMENT] if the index is out of bounds or [ILLEGAL_STATE][naksha.base.NakshaError.ILLEGAL_STATE], if the session to which this result-set is linked was closed.
     */
    abstract fun getObjects(from: Int = 0, to: Int = size, limit: Int = Int.MAX_VALUE, tupleFilter: ITupleFilter? = null, objectFilter: IObjectFilter? = null): AnyObjectList
}