@file:Suppress("OPT_IN_USAGE", "unused")

package naksha.model.request

import naksha.base.*
import naksha.base.FeatureType.FeatureType_C.CATALOG
import naksha.base.FeatureType.FeatureType_C.COLLECTION
import naksha.base.FeatureType.FeatureType_C.FEATURE
import naksha.base.Id.Id_C.ADMIN_CATALOG_ID
import naksha.base.Id.Id_C.BOOKS_COL_ID
import naksha.base.Id.Id_C.CATALOGS_COL_ID
import naksha.base.Id.Id_C.COLLECTIONS_COL_ID
import naksha.base.Id.Id_C.TRANSACTIONS_COL_ID
import naksha.model.objects.NakshaFeature
import naksha.model.objects.NakshaCollection
import naksha.model.objects.NakshaCatalog
import naksha.model.objects.NakshaDatabase
import naksha.model.request.WriteOp.WriteOp_C.CREATE
import naksha.model.request.WriteOp.WriteOp_C.DELETE
import naksha.model.request.WriteOp.WriteOp_C.PURGE
import naksha.model.request.WriteOp.WriteOp_C.UPDATE
import naksha.model.request.WriteOp.WriteOp_C.UPSERT
import kotlin.js.JsExport
import kotlin.js.JsStatic
import kotlin.jvm.JvmOverloads
import kotlin.jvm.JvmStatic

// TODO: Add hints how do a manual correct construction of a write operation

/**
 * A write instruction for the storage.
 *
 * It is **strongly recommended** to use the helper methods to avoid building invalid write instructions.
 *
 * Technically, the storage needs for every write to know where writing should happen, therefore it requires the [databaseId], [catalogId], [collectionId], and the [id]. The new version will be generated by the storage executing the write, so it does not need to be specified, if [version] is given, the current state is expected to exsist in that version _(atomic operation)_.
 *
 * @since 3.0
 */
@JsExport
open class Write : PAnyMap() {

    companion object Write_C {
        /**
         * A special byte-array instance that represents `undefined`.
         * @since 3.0
         */
        private val UNDEFINED_BYTES = "undefined".encodeToByteArray()

        private fun compareCatalogIds(a: String, b: String): Int {
            if (a == b) return 0
            // We order all modifications done in admin-map first.
            if (ADMIN_CATALOG_ID.text == a) return -1
            if (ADMIN_CATALOG_ID.text == b) return 1
            return a.compareTo(b)
        }

        private fun compareCollectionIds(a: String, b: String): Int {
            if (a == b) return 0
            // We order all modifications done in map's collection first (create maps first).
            if (CATALOGS_COL_ID.text == a) return -1
            if (CATALOGS_COL_ID.text == b) return 1
            // We order all modifications done in internal collection's-collection second.
            if (COLLECTIONS_COL_ID.text == a) return -1
            if (COLLECTIONS_COL_ID.text == b) return 1
            // Rest by id
            return a.compareTo(b)
        }

        /**
         * The method to order writes via [MutableList.sortedWith] by:
         * - `catalog-id`
         * - `collection-id`
         * - `partition-number`
         * - `op` (CREATE, UPSERT, UPDATE, DELETE, PURGE, UNKNOWN)
         * - `feature-id`
         *
         * Example:
         * ```kotlin
         * val writes = WriteList()
         * ... add writes
         * writes.sortedWith(Write::sortCompare)
         * ```
         * It is very important that all code that modifies features, use the same ordering.
         *
         * **If writes are not ordered like this, this may lead to concurrent write conflicts and deadlocks in the storage!**
         * @since 3.0
         */
        @JvmStatic
        @JsStatic
        fun sortCompare(a: Write?, b: Write?): Int {
            if (a === b) return 0
            if (b == null) return -1
            if (a == null) return 1

            // Sorts by map-id, collection-id, feature-id.
            // Sorts admin-map, map's collection, and collection's collection first.
            val a_id = a.id
            val b_id = b.id
            val a_catalogId = a.catalogId
            val b_catalogId = b.catalogId
            val a_colId = a.collectionId
            val b_colId = b.collectionId
            val map_diff = compareCatalogIds(a_catalogId.text, b_catalogId.text)
            return if (map_diff == 0) {
                val col_diff = compareCollectionIds(a_colId.text, b_colId.text)
                if (col_diff == 0) {
                    val a_partition = a_id.partitionNumber
                    val b_partition = b_id.partitionNumber
                    val part_diff = a_partition.compareTo(b_partition)
                    if (part_diff == 0) {
                        val id_diff = a_id.compareTo(b_id)
                        if (id_diff == 0) a.op.compareTo(b.op) else id_diff
                    } else part_diff
                } else col_diff
            } else map_diff
        }

        private val ID_NOT_NULL = NotNullIdProperty<Write>(randomId = false)
        private val OP = NotNullEnum<Write, WriteOp>(WriteOp::class) { _, _ -> WriteOp.NULL }
        private val STRING_NULLABLE = NullableProperty<Write, String>(String::class)
        private val INT64_NULLABLE = NullableProperty<Write, Int64>(Int64::class)
        private val FEATURE_NULL = NullableProperty<Write, NakshaFeature>(NakshaFeature::class)
        private val BOOLEAN_FALSE = NotNullProperty<Write, Boolean>(Boolean::class) { _, _ -> false }
    }

    /**
     * The operation to perform.
     * @since 3.0
     */
    var op by OP

    /**
     * @see [op]
     */
    fun withOp(value: WriteOp): Write {
        op = value
        return this
    }

    /**
     * The identifier of the database to write into.
     * @since 3.0
     */
    var databaseId: Id by ID_NOT_NULL

    /**
     * Tests if the [databaseId] is set.
     * @since 3.0
     */
    fun hasDatabaseId(): Boolean = hasIdValue("databaseId")

    /**
     * @see databaseId
     */
    fun withDatabaseId(id: Id): Write {
        this.databaseId = id
        return this
    }

    /**
     * The identifier of the catalog to write into.
     * @since 3.0
     */
    var catalogId: Id by ID_NOT_NULL

    /**
     * Tests if the [catalogId] is set.
     * @since 3.0
     */
    fun hasCatalogId(): Boolean = hasIdValue("catalogId")

    /**
     * @see [catalogId]
     */
    fun withCatalogId(value: Id): Write {
        catalogId = value
        return this
    }

    /**
     * The identifier of the collection to write into.
     *
     * - If a [catalog][NakshaCatalog] should be modified, then [Id.CATALOGS_COL_ID] should be used.
     * - If a [collection][NakshaCollection] should be modified, then [Id.COLLECTIONS_COL_ID] should be used.
     * - If a `book` should be modified, then [Id.BOOKS_COL_ID] should be used.
     * - If a [transactions][naksha.model.objects.NakshaTx] should be modified, then [Id.TRANSACTIONS_COL_ID] should be used.
     * - If a [feature][NakshaFeature] should be modified, then the [NakshaCollection] of the feature should be used.
     * @since 3.0
     * @throws NakshaException with error [NakshaError.ILLEGAL_STATE], if the collection-id is read, before being set.
     */
    var collectionId: Id by ID_NOT_NULL

    /**
     * Tests if the [collectionId] is set.
     * @since 3.0
     */
    fun hasCollectionId(): Boolean = hasIdValue("collectionId")

    /**
     * @see [collectionId]
     */
    fun withCollectionId(value: Id): Write {
        collectionId = value
        return this
    }

    /**
     * If the feature is a fork from another location, the origin.
     * @since 3.0
     */
    var origin: String? by STRING_NULLABLE

    /**
     * @see [origin]
     */
    fun withOrigin(value: String?): Write {
        origin = value
        return this
    }

    /**
     * The expected version that should be modified.
     * @since 3.0
     * @see [atomic]
     */
    var version: Long?
        get() {
            var value = getRaw("version")
            if (value is Number) {
                value = value.toLong()
                setRaw("version", value)
            }
            return value as? Long?
        }
        set(value) {
            if (value == null) removeRaw("version") else setRaw("version", value)
        }

    /**
     * @see [version]
     */
    fun withVersion(value: Long?): Write {
        version = value
        return this
    }

    /**
     * The method should be called after the [databaseId], [catalogId], [collectionId], and [id] have been set. It should be invoked with the raw value read from the [TupleNumber][naksha.model.objects.StandardMembers.StandardMembers_C.TnMember] of the feature to write, see [Member.read][naksha.model.objects.Member.read].
     * @param value the raw value of the [TupleNumber][naksha.model.objects.StandardMembers.StandardMembers_C.TnMember] of the feature that should be modified, read via [Member.read][naksha.model.objects.Member.read].
     * @since 3.0
     * @see [version]
     */
    fun withTupleNumber(value: Any?): Write {
        val tn = value as? TupleNumber ?: if (value is String) TupleNumber.toTupleNumber(value) else null
        if (tn != null) {
            val databaseNumber = this.databaseId.number
            val catalogNumber = this.catalogId.intValue
            val collectionNumber = this.collectionId.intValue
            val featureNumber = this.id.number
            if (tn.databaseNumber != databaseNumber
                || tn.catalogNumber != catalogNumber
                || tn.collectionNumber != collectionNumber
                || tn.featureNumber != featureNumber) {
                origin = value as? String ?: tn.toString()
                version = null
            } else {
                version = tn.version
                atomic = true
                if (op == CREATE) throw illegalState("CREATE operation must not be used for features that exist and have a state identifier (TupleNumber)")
            }
            return this
        }
        // All other values are treated as origin
        origin = value?.toString()
        return this
    }

    /**
     * If this write should be performed atomic.
     *
     * Atomic actions, except for [CREATE][WriteOp.CREATE], does require either [version], or a [TupleNumber] in the [feature].
     *
     * @return `true` if this write should be performed atomic; `false` otherwise.
     * @since 3.0
     * @see [validate]
     * @see [version]
     */
    var atomic: Boolean
        get() = getRaw("atomic") as? Boolean ?: false
        set(value) {
            if (value) setRaw("atomic", true) else removeRaw("atomic")
        }

    /**
     * @see [atomic]
     */
    fun withAtomic(value: Boolean): Write {
        this.atomic = value
        return this
    }

    /**
     * The identifier of the feature to modify.
     * @since 3.0
     * @see withId
     */
    var id: Id
        get() = getRaw("id") as? Id ?: throw illegalState("id is null")
        set(value) {
            setRaw("id", value)
        }

    /**
     * Sets the [id] to the given values.
     * @param id the [id] to set.
     * @return this
     * @since 3.0
     */
    fun withId(id: Id): Write {
        this.id = id
        return this
    }

    /**
     * The new object to persist.
     * @since 3.0
     */
    var `object`: PAnyMap?
        get() = getAs("feature", PAnyMap::class)
        set(value) {
            if (value == null) removeRaw("feature") else setRaw("feature", value)
        }

    /**
     * The new object proxied as [NakshaFeature].
     * @since 3.0
     */
    var feature: NakshaFeature?
        get() = getAs("feature", NakshaFeature::class)
        set(value) {
            if (value == null) removeRaw("feature") else setRaw("feature", value)
        }

    /**
     * @see [feature]
     */
    fun withFeature(value: NakshaFeature?): Write {
        feature = value
        return this
    }

    /**
     * The new object proxied as [NakshaCollection].
     * @since 3.0
     */
    var collection: NakshaCollection?
        get() = feature?.proxy(NakshaCollection::class)
        set(value) { feature = value }

    /**
     * @see [collection]
     */
    fun withCollection(value: NakshaCollection?): Write {
        feature = value
        return this
    }

    /**
     * The new object proxied as [NakshaCatalog].
     * @since 3.0
     */
    var catalog: NakshaCatalog?
        get() = feature?.proxy(NakshaCatalog::class)
        set(value) { feature = value }

    /**
     * @see [collection]
     */
    fun withCatalog(value: NakshaCatalog?): Write {
        catalog = value
        return this
    }

    /**
     * Create a new catalog.
     * @param catalog the catalog to create.
     * @return this.
     * @since 3.0
     */
    fun createCatalog(catalog: NakshaCatalog): Write {
        this.op = CREATE
        this.atomic = true
        this.databaseId = catalog.databaseId
        this.catalogId = ADMIN_CATALOG_ID
        this.collectionId = CATALOGS_COL_ID
        this.id = catalog.id
        this.feature = catalog
        withTupleNumber(catalog.tupleNumberRaw)
        return this
    }

    /**
     * Update a catalog.
     * @param catalog the catalog to update.
     * @param atomic if `true` _(default)_, requires that the catalog exists in the modified state, therefore requires that the given catalog has an embedded [tuple-number][naksha.model.objects.XyzMembers.XyzMembers_C.XyzTn].
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun updateCatalog(catalog: NakshaCatalog, atomic: Boolean = true): Write {
        this.op = UPDATE
        this.atomic = atomic
        this.databaseId = catalog.databaseId
        this.catalogId = ADMIN_CATALOG_ID
        this.collectionId = CATALOGS_COL_ID
        this.id = catalog.id
        this.feature = catalog
        withTupleNumber(catalog.tupleNumberRaw)
        if (atomic && catalog.tupleNumber == null) throw illegalArg("The given catalog '${id}' has no 'tupleNumber' member, atomic operation not possible")
        return this
    }

    /**
     * Try to [CREATE] the catalog, when that fails, because the catalog exists already, perform an [UPDATE], optionally atomic.
     *
     * Actually, an atomic [UPSERT] ignores when another client has deleted the catalog meanwhile, but fails, when there was a concurrent modifications.
     * @param catalog the catalog to update or create.
     * @param atomic applies only to the [UPDATE]; if `true` _(default)_, requires that the catalog exists in a specific state, therefore requires that the given catalog has [tuple-number][naksha.model.objects.XyzMembers.XyzMembers_C.XyzTn].
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun upsertCatalog(catalog: NakshaCatalog, atomic: Boolean = true): Write {
        this.op = UPSERT
        this.atomic = atomic
        this.databaseId = catalog.databaseId
        this.catalogId = ADMIN_CATALOG_ID
        this.collectionId = CATALOGS_COL_ID
        this.id = catalog.id
        this.feature = catalog
        withTupleNumber(catalog.tupleNumberRaw)
        if (atomic && catalog.tupleNumber == null) throw illegalArg("The given catalog '$id' has no 'tupleNumber' member, atomic operation not possible")
        return this
    }

    /**
     * Delete a catalog.
     *
     * Note that an atomic [DELETE] can succeed, even when the given catalog does not have a [TupleNumber] and [atomic] is `true`. However, this requires that the catalog does not exist _(deleting a not existing object is always allowed and successful)_.
     * @param catalog the catalog to delete.
     * @param atomic if `true` _(default)_, requires that the catalog exists in a specific state or not at all.
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteCatalog(catalog: NakshaCatalog, atomic: Boolean = true): Write {
        this.op = DELETE
        this.atomic = atomic
        this.databaseId = catalog.databaseId
        this.catalogId = ADMIN_CATALOG_ID
        this.collectionId = CATALOGS_COL_ID
        this.id = catalog.id
        this.feature = catalog
        withTupleNumber(catalog.tupleNumberRaw)
        return this
    }

    /**
     * Delete a catalog by `id` and optionally version.
     * @param database the database from which to delete the catalog.
     * @param id the `id` of the catalog to delete.
     * @param version if the operation should be performed atomic, the version that is expected to be deleted.
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteCatalogById(database: NakshaDatabase, id: Id, version: Long? = null): Write {
        this.op = DELETE
        this.atomic = version != null
        this.databaseId = database.id
        this.catalogId = ADMIN_CATALOG_ID
        this.collectionId = CATALOGS_COL_ID
        this.id = id
        this.version = version
        return this
    }

    /**
     * Create a Naksha collection in the given map.
     * @param collection the collection to create.
     * @since 3.0
     */
    fun createCollection(collection: NakshaCollection): Write {
        this.op = CREATE
        this.atomic = true
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = COLLECTIONS_COL_ID
        this.id = collection.id
        this.feature = collection
        withTupleNumber(collection.tupleNumberRaw)
        return this
    }

    /**
     * Update a Naksha collection.
     * @param collection the new state of the collection.
     * @param atomic if `true` _(default)_, requires that the collection exists in a specific state, therefore requires that the given collection has [tuple-number][naksha.model.objects.XyzMembers.XyzMembers_C.XyzTn].
     * @since 3.0
     */
    @JvmOverloads
    fun updateCollection(collection: NakshaCollection, atomic: Boolean = true): Write {
        this.op = UPDATE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = COLLECTIONS_COL_ID
        this.id = collection.id
        this.feature = collection
        withTupleNumber(collection.tupleNumberRaw)
        if (atomic && collection.tupleNumber == null) throw illegalArg("The given collection '$id' has no 'tupleNumber' member, atomic operation not possible")
        return this
    }

    /**
     * Try to [CREATE] the collection, when that fails, because the collection exists already, perform an [UPDATE], optionally atomic.
     *
     * Actually, an atomic [UPSERT] ignores when another client has deleted the collection meanwhile, but fails, when there was a concurrent modifications.
     * @param collection the new state of the collection.
     * @param atomic applies only to the [UPDATE]; if `true` _(default)_, requires that the collection exists in a specific state, therefore requires that the given collection has [tuple-number][naksha.model.objects.XyzMembers.XyzMembers_C.XyzTn].
     * @since 3.0
     */
    @JvmOverloads
    fun upsertCollection(collection: NakshaCollection, atomic: Boolean = true): Write {
        this.op = UPSERT
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = COLLECTIONS_COL_ID
        this.id = collection.id
        this.feature = collection
        withTupleNumber(collection.tupleNumberRaw)
        if (atomic && collection.tupleNumber == null) throw illegalArg("The given collection '$id' has no 'tupleNumber' member, atomic UPSERT not possible")
        return this
    }

    /**
     * Delete a Naksha collection.
     *
     * Note that an atomic [DELETE] can succeed, even when the given collection does not have a [TupleNumber] and [atomic] is `true`. However, this requires that the collection does not exist _(deleting a not existing object is always allowed and successful)_.
     * @param collection the collection to delete.
     * @param atomic if _true_ _(default)_, requires that the collection exists in a specific state or not at all.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteCollection(collection: NakshaCollection, atomic: Boolean = true): Write {
        this.op = DELETE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = COLLECTIONS_COL_ID
        this.id = collection.id
        this.feature = collection
        withTupleNumber(collection.tupleNumber)
        return this
    }

    /**
     * Delete a Naksha collection by `id`.
     * @param catalog the catalog from which to delete the collection.
     * @param id the `id` of the collection to delete.
     * @param version if the operation should be performed atomic, the version that is expected to be deleted.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteCollectionById(catalog: NakshaCatalog, id: Id, version: Long? = null): Write {
        this.op = DELETE
        this.atomic = version != null
        this.databaseId = catalog.databaseId
        this.catalogId = catalog.id
        this.collectionId = COLLECTIONS_COL_ID
        this.id = id
        this.version = version
        return this
    }

    /**
     * Create a [NakshaFeature].
     * @param collection the collection in which to create the feature.
     * @param feature the feature to create.
     * @return this.
     * @since 3.0
     */
    fun createFeature(collection: NakshaCollection, feature: NakshaFeature): Write {
        this.op = CREATE
        this.atomic = true
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = feature.id
        this.feature = feature
        withTupleNumber(feature.tupleNumberRaw)
        return this
    }

    /**
     * Update a Naksha feature.
     * @param collection the collection in which to update the feature.
     * @param feature the new state of the feature.
     * @param atomic if _true_ _(default)_, requires that the feature exists in a specific state, therefore requires that the given feature has a [tuple-number][naksha.model.objects.XyzMembers.XyzMembers_C.XyzTn].
     * @since 3.0
     */
    @JvmOverloads
    fun updateFeature(collection: NakshaCollection, feature: NakshaFeature, atomic: Boolean = true): Write {
        this.op = UPDATE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = feature.id
        this.feature = feature
        withTupleNumber(feature.tupleNumberRaw)
        if (atomic && feature.tupleNumber == null) throw illegalArg("The given feature '$id' has no 'tupleNumber' member, atomic UPDATE not possible")
        return this
    }

    /**
     * Try to [CREATE] the feature, when that fails, because the feature exists already, perform an [UPDATE], optionally atomic.
     *
     * Actually, an atomic [UPSERT] ignores when another client has deleted the feature meanwhile, but fails, when there was a concurrent modifications.
     * @param collection the collection in which to create or update the feature.
     * @param feature the new state of the feature.
     * @param atomic applies only to the [UPDATE]; if `true` _(default)_, requires that the collection exists in a specific state, therefore requires that the given collection has [tuple-number][naksha.model.objects.XyzMembers.XyzMembers_C.XyzTn].
     * @since 3.0
     */
    @JvmOverloads
    fun upsertFeature(collection: NakshaCollection, feature: NakshaFeature, atomic: Boolean = true): Write {
        this.op = UPSERT
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = feature.id
        this.feature = feature
        withTupleNumber(feature.tupleNumberRaw)
        return this
    }

    /**
     * Delete a Naksha feature.
     *
     * Note that an atomic [DELETE] can succeed, even when the given feature does not have a [TupleNumber] and [atomic] is `true`. However, this requires that the feature does not exist _(deleting a not existing object is always allowed and successful)_.
     * @param collection the collection from which to delete the feature.
     * @param feature the feature to delete.
     * @param atomic if `true` _(default)_, requires that the feature exists in a specific state or not at all.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteFeature(collection: NakshaCollection, feature: NakshaFeature, atomic: Boolean = true): Write {
        this.op = DELETE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = feature.id
        this.feature = feature
        withTupleNumber(feature.tupleNumberRaw)
        return this
    }

    /**
     * Delete a feature by `id` and optionally version.
     * @param collection the collection from which to delete the feature.
     * @param id the `id` of the feature to delete.
     * @param version if the operation should be performed atomic, the version that is expected to be deleted.
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteFeatureById(collection: NakshaCollection, id: Id, version: Long? = null): Write {
        this.op = DELETE
        this.atomic = version != null
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = id
        this.version = version
        return this
    }

    /**
     * Purge a Naksha feature
     *
     * This means to delete potentially pending tombstones in _HEAD_ section and to move them into _HISTORY_. This operation is special and normally only needed when views are used to revert back to the original _(otherwise shadowed)_ state. In a normal situation there is totally no need to do this. That is why there is no [PURGE] available for database, catalog or collection.
     * @param collection the collection from which to purge the feature.
     * @param feature the feature to purge.
     * @param atomic if `true` _(default)_, requires that the feature exists in a specific state or not at all.
     * @since 3.0
     */
    @JvmOverloads
    fun purgeFeature(collection: NakshaCollection, feature: NakshaFeature, atomic: Boolean = true): Write {
        this.op = PURGE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = feature.id
        withTupleNumber(feature.tupleNumberRaw)
        return this
    }

    /**
     * Purge a feature by `id`.
     *
     * This means to delete potentially pending tombstones in _HEAD_ section and to move them into _HISTORY_. This operation is special and normally only needed when views are used to revert back to the original _(otherwise shadowed)_ state. In a normal situation there is totally no need to do this. That is why there is no [PURGE] available for database, catalog or collection.
     * @param collection the collection from which to purge the feature.
     * @param id the identifier of the feature to purge.
     * @param version if the operation should be performed atomic, the version that is expected to be deleted.
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun purgeFeatureById(collection: NakshaCollection, id: Id, version: Long? = null): Write {
        this.op = PURGE
        this.atomic = version != null
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = id
        this.version = version
        return this
    }

    /**
     * Create an object.
     * @param collection the collection in which to create the object.
     * @param obj the object to create.
     * @return this.
     * @since 3.0
     */
    fun createObject(collection: NakshaCollection, obj: PAnyMap): Write {
        this.op = CREATE
        this.atomic = true
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = collection.readId(obj)
        this.`object` = obj
        withTupleNumber(collection.readTupleNumberRaw(obj))
        return this
    }

    /**
     * Update an object.
     * @param collection the collection in which to update the object.
     * @param obj the new state of the object.
     * @param atomic if _true_ _(default)_, requires that the object exists in a specific state, therefore requires that the given object has a tuple-number.
     * @since 3.0
     */
    @JvmOverloads
    fun updateObject(collection: NakshaCollection, obj: PAnyMap, atomic: Boolean = true): Write {
        this.op = UPDATE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = collection.readId(obj)
        this.`object` = obj
        withTupleNumber(collection.readTupleNumberRaw(obj))
        return this
    }

    /**
     * Try to [CREATE] the object, when that fails, because the object exists already, perform an [UPDATE], optionally atomic.
     *
     * Actually, an atomic [UPSERT] ignores when another client has deleted the object meanwhile, but fails, when there was a concurrent modifications.
     * @param collection the collection in which to create or update the object.
     * @param obj the new state of the object.
     * @param atomic applies only to the [UPDATE]; if `true` _(default)_, requires that the collection exists in a specific state, therefore requires that the given collection has [tuple-number][naksha.model.objects.XyzMembers.XyzMembers_C.XyzTn].
     * @since 3.0
     */
    @JvmOverloads
    fun upsertObject(collection: NakshaCollection, obj: PAnyMap, atomic: Boolean = true): Write {
        this.op = UPSERT
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = collection.readId(obj)
        this.`object` = obj
        withTupleNumber(collection.readTupleNumberRaw(obj))
        return this
    }

    /**
     * Delete an object.
     *
     * Note that an atomic [DELETE] can succeed, even when the given object does not have a [TupleNumber] and [atomic] is `true`. However, this requires that the object does not exist _(deleting a not existing object is always allowed and successful)_.
     * @param collection the collection from which to delete the object.
     * @param obj the object to delete.
     * @param atomic if `true` _(default)_, requires that the object exists in a specific state or not at all.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteObject(collection: NakshaCollection, obj: PAnyMap, atomic: Boolean = true): Write {
        this.op = DELETE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = collection.readId(obj)
        this.`object` = obj
        withTupleNumber(collection.readTupleNumberRaw(obj))
        return this
    }

    /**
     * Delete an object by `id` and optionally version.
     * @param collection the collection from which to delete the object.
     * @param id the `id` of the object to delete.
     * @param version if the operation should be performed atomic, the version that is expected to be deleted.
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun deleteObjectById(collection: NakshaCollection, id: Id, version: Long? = null): Write {
        this.op = DELETE
        this.atomic = version != null
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = id
        this.version = version
        return this
    }

    /**
     * Purge an object.
     *
     * This means to delete potentially pending tombstones in _HEAD_ section and to move them into _HISTORY_. This operation is special and normally only needed when views are used to revert back to the original _(otherwise shadowed)_ state. In a normal situation there is totally no need to do this. That is why there is no [PURGE] available for database, catalog or collection.
     * @param collection the collection from which to purge the object.
     * @param obj the object to purge.
     * @param atomic if `true` _(default)_, requires that the object exists in a specific state or not at all.
     * @since 3.0
     */
    @JvmOverloads
    fun purgeObject(collection: NakshaCollection, obj: PAnyMap, atomic: Boolean = true): Write {
        this.op = PURGE
        this.atomic = atomic
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = collection.readId(obj)
        withTupleNumber(collection.readTupleNumberRaw(obj))
        return this
    }

    /**
     * Purge an object by `id`.
     *
     * This means to delete potentially pending tombstones in _HEAD_ section and to move them into _HISTORY_. This operation is special and normally only needed when views are used to revert back to the original _(otherwise shadowed)_ state. In a normal situation there is totally no need to do this. That is why there is no [PURGE] available for database, catalog or collection.
     * @param collection the collection from which to purge the object.
     * @param id the identifier of the object to purge.
     * @param version if the operation should be performed atomic, the version that is expected to be deleted.
     * @return this.
     * @since 3.0
     */
    @JvmOverloads
    fun purgeObjectById(collection: NakshaCollection, id: Id, version: Long? = null): Write {
        this.op = PURGE
        this.atomic = version != null
        this.databaseId = collection.databaseId
        this.catalogId = collection.catalogId
        this.collectionId = collection.id
        this.id = id
        this.version = version
        return this
    }

    // TODO: Add more helpers for:
    //       pojos: createPojo, updatePojo, upsertPojo, deletePojo, purgePojo
    //          These methods need not only members, but as well annotations on the given objects and we need to patch the JbEncoder2/JbDecoder2
    //          This will only work on JVM implementation, therefore we need to somehow make them platform dependend.
    //          Maybe we offer a JvmWrite as JVM only implementation in a dedicated library, extending the Write?
    //          We could simply convert the POJOs on-the-fly into arbitrary objects and use the objects, so it is transparent for the user?
    //          This is a requirement for map-feedback and all code that uses Jackson!
    //          This would eventually be helpful as well for earthcore, because we can use the POJOs.
    //          If possible, we should implement it as JVM only implementation in the core libraries, without including jackson
    //          Actually we can find Jackson annotations at runtime using reflection, no need to include jackson!

    /**
     * Tests if this write modifies a catalog.
     *
     * @return `true` if this write modifies a catalog; `false` otherwise.
     * @since 3.0
     */
    fun isCatalogModification(): Boolean = catalogId == ADMIN_CATALOG_ID && collectionId == CATALOGS_COL_ID

    /**
     * Tests if this write modifies a collection.
     *
     * @return `true` if this write modifies a collection; `false` otherwise.
     * @since 3.0
     */
    fun isCollectionModification(): Boolean = collectionId == COLLECTIONS_COL_ID

    /**
     * Tests if this write modifies a book.
     *
     * @return `true` if this write modifies a book; `false` otherwise.
     * @since 3.0
     */
    fun isBookModification(): Boolean = catalogId == ADMIN_CATALOG_ID && collectionId == BOOKS_COL_ID

    /**
     * Tests if this write modifies a book.
     *
     * @return `true` if this write modifies a book; `false` otherwise.
     * @since 3.0
     */
    fun isTransactionModification(): Boolean = catalogId == ADMIN_CATALOG_ID && collectionId == TRANSACTIONS_COL_ID

    /**
     * Tests if this write modifies a feature within a collection.
     *
     * @return `true` if this write modifies a feature within a collection; `false` otherwise.
     * @since 3.0
     */
    fun isFeatureModification(): Boolean = !isCatalogModification()
            && !isCollectionModification()
            && !isBookModification()
            && !isTransactionModification()

    /**
     * Validate that this write is valid, invoked by [session's][naksha.model.ISession] before executing the writes. This is just a simple pre-validation, storages have to do final checks.
     *
     * @since 3.0
     * @see [atomic]
     * @see [WriteOp]
     * @throws NakshaException with error [NakshaError.ILLEGAL_STATE], if the write is invalid.
     */
    fun validate(): Write {
        // Writing into the admin-catalog means that we want to mutate administrative objects.
        if (catalogId == ADMIN_CATALOG_ID) {
            if (collectionId == CATALOGS_COL_ID) { // Mutation of catalog.
                CATALOG.verify(id.text)
            } else if (collectionId == BOOKS_COL_ID) { // Mutation of book.
                FeatureType.BOOK.verify(id.text)
            } else if (collectionId == COLLECTIONS_COL_ID) { // Mutation of collection.
                COLLECTION.verify(id.text)
            } else if (collectionId == TRANSACTIONS_COL_ID) { // Mutation of transaction.
                FeatureType.TRANSACTION.verify(id.text)
            } else {
                throw illegalArg("Write operation for invalid collection in admin catalog; id: '$id' ")
            }
            return this
        } else if (collectionId == COLLECTIONS_COL_ID) { // Mutation of collection in custom catalog.
            COLLECTION.verify(id.text)
        } else { // arbitrary feature is modified, we allow any identifier, as long as it is in valid range.
            CATALOG.verify(catalogId.text)
            COLLECTION.verify(catalogId.text)
            FEATURE.verify(id.text)
        }
        return this
    }
}