@file:Suppress("OPT_IN_USAGE")

package naksha.model

import naksha.base.Int64
import kotlin.js.JsExport
import kotlin.jvm.JvmField

/**
 * The metadata about a [Row] generated by the storage, read-only for the client.
 */
@JsExport
data class Metadata(
    @JvmField
    val updatedAt: Int64,
    @JvmField
    val createdAt: Int64,
    @JvmField
    val authorTs: Int64,
    @JvmField
    val txnNext: Int64?,
    @JvmField
    val txn: Int64,
    @JvmField
    val ptxn: Int64?,
    @JvmField
    val uid: Int,
    @JvmField
    val puid: Int,
    @JvmField
    val fnva1: Int, // TODO: Rename to hash
    @JvmField
    val version: Int,
    @JvmField
    val geoGrid: Int,
    @JvmField
    val flags: Int,
    @JvmField
    val origin: String?,
    @JvmField
    val appId: String,
    @JvmField
    val author: String?,
    @JvmField
    val type: String?,
    @JvmField
    val id: String
) {

    fun getLuid() = Luid(Txn(txn), uid)
}