package com.here.naksha.cli;
import picocli.CommandLine;
// This file is auto-generated by Gradle. ANY CHANGE WILL BE OVERWRITTEN!
public final class VersionInfo implements CommandLine.IVersionProvider {
    @Override
    public String[] getVersion() {
        return new String[] {"naksha-cli 0.1.0"};
    }
    private VersionInfo() {}
}