@file:Suppress("OPT_IN_USAGE")

package naksha.auth

import naksha.base.AnyObject
import naksha.base.Platform.Platform_C.forKClass
import naksha.base.PlatformType
import kotlin.js.JsExport
import kotlin.js.JsStatic
import kotlin.jvm.JvmField

/**
 * The base class for service operation parameters _(the parameter-set of an operation)_.
 *
 * The values of the parameters are limited, they must be of one of the following types:
 * - `Scalar` _(`null`, `String`, `Double`, `Int`, or `Int64`)_
 * - `List<Scalar>`
 * - `Map<String, Scalar>`
 *
 * This is generated by an application or service, when a user tries to execute an operation. Each operation execution needs a [parameter-set][ServiceOpParams], but operations can share [parameter-set's][ServiceOpParams], if they require the same parameters. For example, the `createFeatures`, `updateFeatures` and `deleteFeatures` operations may share a [parameter-set][ServiceOpParams] named `WriteFeaturesParams`.
 *
 * Therefore, parameter values may be flat lists or flat maps, but no nested lists or nested maps!
 * @since 3.0
 * @see ServiceOpParamsList
 * @see ServiceOps
 */
@JsExport
open class ServiceOpParams : AnyObject() {
    companion object ServiceOpParams_C {
        /**
         * The [PlatformType] of [ServiceOpParams].
         * @since 3.0
         */
        @JvmField
        @JsStatic
        val TYPE: PlatformType<ServiceOpParams> = forKClass(ServiceOpParams::class).withPackageName(PACKAGE_NAME)
    }
}