@file:Suppress("OPT_IN_USAGE")

package naksha.base

import kotlin.js.JsExport
import kotlin.reflect.KClass

/**
 * A platform type wrapper that wraps a native type, for example a Java `Class`, so that it works cross-platform, where types are needed.
 *
 * @since 3.0
 */
@JsExport
interface PlatformType<T> {

    /**
     * The full qualified name of the type.
     *
     * In _Java_ this is the same as `Class.getName`, in JavaScript_ this name must be generated by iterating `globalThis` and searching for the path to the constructor of the type. This is expensive, but only done ones per type, when [initialize] is invoked the first time.
     * @since 3.0
     */
    val name: String

    /**
     * The package name of this type.
     *
     * In _Java_ this is the same as `Class.getPackageName`, in JavaScript_ this name must be generated by iterating `globalThis` and searching for the path to the constructor of the type. This is expensive, but only done ones per type, when [initialize] is invoked the first time.
     */
    val packageName: String

    /**
     * Helper method to manually set the package-name.
     *
     * @param packageName The [packageName] of this type.
     * @return this.
     * @since 3.0
     */
    fun withPackageName(packageName: String): PlatformType<T>

    /**
     * The simple name of the type.
     *
     * In _Java_ this is the same as `Class.getSimpleName`. In _JavaScript_ this is the same as `constructor.name`.
     * @since 3.0
     */
    val simpleName: String

    /**
     * The symbol to which this platform type belongs.
     *
     * The default value is always [Platform.DEFAULT_SYMBOL], so that all types are in the default symbol, being `com.here.naksha`.
     * @since 3.0
     */
    var symbol: Symbol

    /**
     * Helper method to manually set the default symbol.
     *
     * @param symbol The default [Symbol] for this type.
     * @return this.
     * @since 3.0
     */
    fun withSymbol(symbol: Symbol): PlatformType<T>

    /**
     * If not being `null`, then this value is used by JSON encoder/decoder as type-name when serializing or deserializing.
     * @since 3.0
     */
    var jsonType: String?

    /**
     * Helper method to set the [jsonType].
     *
     * @param jsonType The JSON type name to set.
     * @return this.
     * @since 3.0
     */
    fun withJsonType(jsonType: String?): PlatformType<T>

    /**
     * Helper method to set the [jsonType] to [name], which will force the [Platform.toJSON] method to inject the `type` property with the value as specified in [jsonType]. This allows the deserializer _([Platform.fromJson])_ to restore the correct object type or [Proxy].
     *
     * @return this.
     * @since 3.0
     */
    fun withNameAsJsonType(): PlatformType<T>

    /**
     * The native platform type that is wrapped.
     *
     * In _Java_ this is the `Class`, in _JavaScript_ the `constructor`, so a function.
     * @since 3.0
     */
    val nativeClass: Any

    /**
     * The Kotlin klass representing this type.
     * @since 3.0
     */
    @Suppress("NON_EXPORTABLE_TYPE")
    val kotlinClass: KClass<*>

    /**
     * If this type can be instantiated via [newInstance], that means it is not an interface, abstract, and does have a parameterless constructor.
     * @since 3.0
     */
    val isInstantiatable: Boolean

    /**
     * Initialize the class.
     *
     * This will cause all static init-code to be invoked, and ensures that all static properties have correct values. If the class is already initialized, does nothing. Normally, Java and JavaScript do initialize classes lazy, so not before needed. However, some classes create static properties, which register them self with some registry, in that case the class should be initialized when the application starts. This is for example the case for enumerations.
     * @since 3.0
     */
    fun initialize()

    /**
     * Call the parameterless constructor of the type using platform specific methods.
     *
     * - Throws [NakshaError.ILLEGAL_STATE] if either the type does not have a parameterless constructor, or is an interface or abstract.
     * @return the new type.
     * @since 3.0
     */
    fun newInstance(): T

    /**
     * Create a new instance of this type, bypassing the constructor, so it returns an uninitialized object _(not calling the constructor)_.
     *
     * ## Warning
     * Not calling the constructor can leave properties in an uninitialized state, and is normally only done by deserialization tools. Another usage of this method is the runtime creation of [proxies][Proxy], when adding them to [SymbolMember] via [proxy] method.
     *
     * @return the new object.
     * @since 3.0
     */
    fun allocate(): T

    /**
     * Tests if the [target] type can be cast _(widened)_ to this type, so if **`target as this`** is possible.
     *
     * More specific, tests if the [target] class or interface is either the same as, or is a superclass or superinterface of, the class or interface represented by this.
     *
     * For example, assume `fooType` is a `PlatformType<String>`, then `foo.isAssignableFrom(ofKotlin(CharSequence::class))` would be _false_, because not every [CharSequence] is always a [String].
     *
     * However, if `foo` is a `PlatformType<CharSequence>`, then `foo.isAssignableFrom(ofKotlin(String::class))` will be _true_, because every [String] is always a [CharSequence].
     *
     * **Warning**: An assignment is not the same as an instanceof test. For example for interfaces the example can be tricky, because formally the cast from a [CharSequence] to a [String] is not an assignable form, but technically can still succeed, if the object being tried to cast down is actually a string, just the compiler type is formally [CharSequence]. Formally this kind of cast is an assignment from [String] to [String] not being known at compile time.
     *
     * @param target The target type from which to cast.
     * @return _true_ if the [target] type can be cast to this type in all cases; _false_ otherwise.
     * @since 3.0
     */
    fun isAssignableFrom(target: PlatformType<*>): Boolean

    /**
     * Tests if this type can be cast _(widened)_ to the [target] type, so if **`this as target`** is possible.
     *
     * More specific, tests if this class or interface is either the same as, or is a superclass or superinterface of, the class or interface represented by [target].
     *
     * For example, assume `fooType` is a `PlatformType<CharSequence>`, then `foo.isAssignableTo(ofKotlin(String::class))` would be _false_, because not every [CharSequence] is always a [String].
     *
     * However, if `foo` is a `PlatformType<String>`, then `foo.isAssignableTo(ofKotlin(CharSequence::class))` will be _true_, because every [String] is always a [CharSequence].
     *
     * **Warning**: An assignment is not the same as an instanceof test. For example for interfaces the example can be tricky, because formally the cast from a [CharSequence] to a [String] is not an assignable form, but technically can still succeed, if the object being tried to cast down is actually a string, just the compiler type is formally [CharSequence]. Formally this kind of cast is an assignment from [String] to [String] not being known at compile time.
     *
     * @param target The target type to which to cast.
     * @return _true_ if this type can be cast to the [target] type in all cases; _false_ otherwise.
     * @since 3.0
     */
    fun isAssignableTo(target: PlatformType<*>): Boolean

    /**
     * Test if the given target is an instance of this type.
     * @param target the target to test.
     * @return _true_ if the given target is an instance of this type; _false_ otherwise.
     * @since 3.0
     */
    fun isInstance(target: Any?): Boolean

    /**
     * Tests if this type is a [Proxy].
     *
     * @return _true_ if this type is a [Proxy]; _false_ otherwise.
     * @since 3.0
     */
    fun isProxy(): Boolean

    /**
     * If this is a proxy, and the given object is an [PlatformObject], then return an instance of this type from the [SymbolMember] bound to the [symbol] of this type.
     *
     * This method logically does:
     * - If this type is no [Proxy], throw [NakshaError.ILLEGAL_STATE].
     * - If the given object is no [PlatformObject], throw [NakshaError.ILLEGAL_ARGUMENT].
     * - If the given [PlatformObject] does not have an existing [SymbolMember] for [symbol], create one.
     * - If the [SymbolMember] does not contain an instance of this type, create a [new instance][newInstance] and store it in the [SymbolMember].
     * - Return the value from the [SymbolMember].
     *
     * Kotlin-Usage:
     * ```kotlin
     * val bar = Platform.forKClass(Bar::class).proxy(foo)
     * ```
     * Java-Usage:
     * ```java
     * Bar bar = Platform.forClass(Bar.class).proxy(foo);
     * ```
     * JavaScript-Usage:
     * ```javascript
     * let bar = Platform.forJsClass(Bar).proxy(foo);
     * ```
     * It's recommended to import `naksha.base.PlatformType.{for...Class}` statically, so that `forKClass`, `forClass` and/or `forJsClass` can be used directly.
     * @param o The [PlatformObject] to query.
     * @return an instance of this type.
     * @since 3.0
     */
    fun proxy(o: Any?): T

    /**
     * If this is a proxy and the given [PlatformObject] does have an instance of this type bound to the given `symbol` or `null`.
     *
     * This method logically does:
     * - If this type is no [Proxy], return `null`
     * - If the given [PlatformObject] does not have an existing [SymbolMember] for `symbol`, return `null`.
     * - If the [SymbolMember] does not contain an instance of this type, return `null`.
     * - Return the bound instance of this from the [SymbolMember] value.
     *
     * @param o the [PlatformObject] to read from.
     * @param symbol the [Symbol] to read.
     * @return the bound proxy instance of this type, or `null`, if no instance of this is bound to the given [PlatformObject].
     * @since 3.0
     */
    fun getProxy(o: Any?, symbol: Symbol = this.symbol): T?

   /**
    * If this is a proxy, return an instance of this type from the [SymbolMember] bound to the given `symbol`.
    *
    * This method logically does:
    * - If this type is no [Proxy], throw [NakshaError.ILLEGAL_STATE].
    * - If the given [PlatformObject] does not have an existing [SymbolMember] for `symbol`, create one.
    * - If the [SymbolMember] does not contain an instance of this type, create a [new instance][newInstance] and store it in the [SymbolMember].
    * - Return the value from the [SymbolMember].
    *
     * @param o the [PlatformObject] to link this proxy with _(if this is a [Proxy])_.
     * @param symbol the [Symbol] to link the proxy against.
     * @return the linked proxy.
     * @since 3.0
     */
    fun getOrCreateProxy(o: Any?, symbol: Symbol = this.symbol): T

    /**
     * Cast the given object into this type, if possible. The value `null` always result in `null`.
     *
     * - [NakshaError.ILLEGAL_ARGUMENT] - if the given argument can't be cast to this type.
     * @param o the object to cast.
     * @return the object cast to this type.
     * @since 3.0
     */
    fun cast(o: Any?): T?
}