@file:Suppress("OPT_IN_USAGE")

package naksha.model.objects

import naksha.base.Int64
import naksha.base.JsEnum
import naksha.geo.SpGeometry
import naksha.base.NakshaError.NakshaErrorCompanion.INITIALIZATION_FAILED
import naksha.base.NakshaException
import naksha.base.Platform.PlatformCompanion.fromJSON
import naksha.model.TagMap
import naksha.base.TupleNumber
import naksha.base.proxy
import naksha.geo.GeoUtil
import naksha.model.TagList
import naksha.model.TagNormalizer.TagNormalizer_C.normalizeTag
import kotlin.js.JsExport
import kotlin.jvm.JvmField
import kotlin.jvm.JvmOverloads
import kotlin.reflect.KClass

/**
 * The type of [Member]. The type defines what the storage expects as value in the member book of the [Tuple][naksha.model.Tuple], either as _HEAP_ object or as binary.
 *
 * The member book is generated by the [encoder][naksha.model.Tuple.encodeFeature], which must produce the values in the defined [MemberType] from the given input feature _(for example [NakshaFeature])_.
 *
 * The [decoder][naksha.model.Tuple.decodeFeature] reverses this. It receives a [Tuple][naksha.model.Tuple] from the storage which contains the [Member] values in the defined [MemberType] and integrates them back into the output feature _(for example [NakshaFeature])_.
 *
 * - [BOOLEAN], [INT8], [INT16], [INT32], [INT64], [FLOAT32], [FLOAT64], [STRING], [BYTE_ARRAY] —> Primitives.
 * - [SPATIAL] —> A geometry represented in memory as [SpGeometry] and binary as [TWKB](https://github.com/TWKB/Specification/blob/master/twkb.md).
 * - [TAG_LIST] —> A list of strings _([TagList])_. The order is significant and guaranteed. The storage persists the list unmodified, so the element order is guaranteed to be preserved when reading back from the storage.
 * - [TAG_MAP] —> A map with keys being strings and values being primitives _([TagMap])_. The order of the key-value pairs is not guaranteed by the storage, when converted into a [Member].
 * @since 3.0
 */
@JsExport
class MemberType : JsEnum() {

    @Suppress("NON_EXPORTABLE_TYPE")
    override fun namespace(): KClass<out JsEnum> = MemberType::class

    override fun initClass() {}

    companion object MemberType_C {
        // TODO: We need to update the documentation of the members, so that they match the up-to-date one provided for the class!

        /**
         * [Boolean] — Boolean.
         * @since 3.0
         */
        @JvmField
        val BOOLEAN = defIgnoreCase(MemberType::class, "boolean") {
            self -> self.sortOrder = 6
            self.subtype = BoolMember::class
            self.valuesType = Boolean::class
        }

        /**
         * [Byte] — 8-bit signed integer in storage, but when reading from book.
         * @since 3.0
         */
        @JvmField
        val INT8 = defIgnoreCase(MemberType::class, "int8") {
            self -> self.sortOrder = 5
            self.subtype = Int16Member::class
            self.valuesType = Int::class
        }

        /**
         * [Short] — 16-bit signed integer in storage, but when reading from book.
         * @since 3.0
         */
        @JvmField
        val INT16 = defIgnoreCase(MemberType::class, "int16") {
            self -> self.sortOrder = 4
            self.subtype = Int16Member::class
            self.valuesType = Int::class
        }

        /**
         * [Int] — 32-bit signed integer in storage, but when reading from book.
         * @since 3.0
         */
        @JvmField
        val INT32 = defIgnoreCase(MemberType::class, "int32") {
            self -> self.sortOrder = 2
            self.subtype = Int32Member::class
            self.valuesType = Int::class
        }

        /**
         * [Long] — 64-bit signed integer.
         * @since 3.0
         */
        @JvmField
        val INT64 = defIgnoreCase(MemberType::class, "int64") {
            self -> self.sortOrder = 0
            self.subtype = Int64Member::class
            self.valuesType = Long::class
        }

        /**
         * [Float] — 32-bit IEEE-754 floating point in storage, but when reading from book.
         * @since 3.0
         */
        @JvmField
        val FLOAT32 = defIgnoreCase(MemberType::class, "float32") {
            self -> self.sortOrder = 3
            self.subtype = Float32Member::class
            self.valuesType = Float::class
        }

        /**
         * [Double] — 64-bit IEEE-754 floating point.
         * @since 3.0
         */
        @JvmField
        val FLOAT64 = defIgnoreCase(MemberType::class, "float64") {
            self -> self.sortOrder = 1
            self.subtype = Float64Member::class
            self.valuesType = Double::class
        }

        /**
         * [String] — Variable-length string.
         * @since 3.0
         */
        @JvmField
        val STRING = defIgnoreCase(MemberType::class, "string") {
            self -> self.sortOrder = 7
            self.subtype = StringMember::class
            self.valuesType = String::class
        }

        /**
         * [ByteArray] — Raw bytes.
         * @since 3.0
         */
        @JvmField
        val BYTE_ARRAY = defIgnoreCase(MemberType::class, "byte_array") {
            self -> self.sortOrder = 12
            self.subtype = ByteArrayMember::class
            self.valuesType = ByteArray::class
        }

        /**
         * [TupleNumber] — A tuple-number, represented as [TupleNumber].
         * @since 3.0
         */
        @JvmField
        val TUPLE_NUMBER = defIgnoreCase(MemberType::class, "tuple_number") {
            self -> self.sortOrder = 11
            self.subtype = TupleNumberMember::class
            self.valuesType = TupleNumber::class
        }

        /**
         * [SpGeometry] — A GeoJSON geometry, the binary representation are [TWKB](https://github.com/nicowillis/twkb) bytes.
         * @since 3.0
         */
        @JvmField
        val SPATIAL = defIgnoreCase(MemberType::class, "spatial") {
            self -> self.sortOrder = 10
            self.subtype = SpatialMember::class
            self.valuesType = SpGeometry::class
        }


        /**
         * [TagList] — A list of strings.
         *
         * This is the default type of the standard `tags` member in the classic XYZ format, which encodes the `tags` in the `JSON` object at `properties->@ns:com:here:xyz->tags`, example:
         * ```json
         * {
         *   "properties": {
         *     "@ns:com:here:xyz": {
         *       "tags": ["foo", "bar"]
         *     }
         *   }
         * }
         * ```
         * @since 3.0
         */
        @JvmField
        val TAG_LIST = defIgnoreCase(MemberType::class, "tag_list") {
            self -> self.sortOrder = 9
            self.subtype = TagListMember::class
            self.valuesType = TagList::class
        }

        /**
         * [TagMap] — A map whose keys are strings and values are primitives.
         * @since 3.0
         */
        @JvmField
        val TAG_MAP = defIgnoreCase(MemberType::class, "tag_map") {
            self -> self.sortOrder = 8
            self.subtype = TagMapMember::class
            self.valuesType = TagMap::class
        }

       init {
            // Validate sort orders form a contiguous range [0, N); done here, after all types have loaded.
            // Note: This order is used to sort members in storages.
            // We first want all fixed size items with 8 byte, then 4 bytes, 2 byte, 1 byte, then flexible types.
            val orders = ArrayList<Int>()
            val i = iterate(MemberType::class)
            while (i.hasNext()) orders.add(i.next().sortOrder)
            orders.sort()
            for (idx in orders.indices) {
                if (orders[idx] != idx) throw NakshaException(
                    INITIALIZATION_FAILED,
                    "MemberType sort orders must be contiguous starting at 0; expected $idx but found ${orders[idx]} (all sorted: $orders)"
                )
            }
        }
    }

    /**
     * The Kotlin type that generally represents this member type.
     *
     * Beware the for primitives technically smaller values are as well accepted, therefore use [isInstance] to test if a value is valid for a certain member type and not the `isInstance` method of this class!
     *
     * The intent for this property is debugging purpose, for example `"exepcted ${memberType.valueType.simpleName}"`, which may print something like `"expected Long"` or `"expected TagMap"`.
     * @since 3.0
     */
    var valuesType: KClass<*> = Any::class
        private set

    /**
     * The subtype of this class, so the specialized member type, for example [StringMember].
     * @since 3.0
     */
    var subtype: KClass<out Member> = Member::class
        private set

    /**
     * Tests if the given value is of this type.
     *
     * **Note**: For [TAG_MAP_FROM_TAG_LIST] the expectation is [TagList], **not** [TagMap]!
     * @param value the value to test.
     * @return `true` if the value is of this type; false otherwise.
     */
    fun isInstance(value: Any?): Boolean {
        return value != null && when (this) {
            BOOLEAN -> value is Boolean
            INT8 -> value is Byte
            INT16 -> value is Byte || value is Short
            INT32 -> value is Byte || value is Short || value is Int
            INT64 -> value is Byte || value is Short || value is Int || value is Long || value is Int64
            FLOAT32 -> value is Float
            FLOAT64 -> value is Float || value is Double
            STRING -> value is String
            BYTE_ARRAY -> value is ByteArray
            TUPLE_NUMBER -> value is TupleNumber
            SPATIAL -> value is SpGeometry
            TAG_MAP -> value is TagMap
            TAG_LIST -> value is TagList
            else -> false
        }
    }

    /**
     * Converts the given value into the expected format of the type or returns `null`. For example for [INT8] numbers will be cast into [Byte].
     * @param value the value to convert.
     * @param normalize only for [TAG_LIST], if the value should be normalized or are from a trusted source.
     * @return the converted value or `null`.
     * @since 3.0
     */
    @JvmOverloads
    fun convert(value: Any?, normalize: Boolean = true): Any? = when (this) {
        INT8 -> if (value is Number) value.toByte() else if (value is Int64) value.toByte() else null
        INT16 -> if (value is Number) value.toShort() else if (value is Int64) value.toShort() else null
        INT32 -> if (value is Number) value.toInt() else if (value is Int64) value.toInt() else null
        INT64 -> if (value is Number) value.toLong() else if (value is Int64) value.toLong() else null
        FLOAT32 -> if (value is Number) value.toFloat() else if (value is Int64) value.toFloat() else null
        FLOAT64 -> if (value is Number) value.toDouble() else if (value is Int64) value.toDouble() else null
        STRING -> value as? String ?: if (value is Char || value is CharSequence) value.toString() else null
        BYTE_ARRAY -> value as? ByteArray
        TUPLE_NUMBER -> value as? TupleNumber ?:
                        if (value is String) TupleNumber.fromString(value)
                        else if (value is ByteArray) TupleNumber.fromByteArray(value)
                        else null
        SPATIAL -> value as? SpGeometry ?:
                        if (value is String) fromJSON(value).proxy(SpGeometry::class)
                        else if (value is ByteArray) GeoUtil.fromTWKB(value)
                        else value.proxy(SpGeometry::class)
        TAG_LIST -> value as? TagList ?:
                    if (value is Array<*>) TagList.fromArray(value)
                    else if (value is String) fromJSON(value).proxy(TagList::class)
                    else value.proxy(TagList::class)
        TAG_MAP -> value as? TagMap ?:
                   if (value is String) fromJSON(value).proxy(TagMap::class)
                   else value.proxy(TagMap::class)
        else -> null
    }

    /**
     * The sort order of the type to ensure no padding is needed, so `INT8`, `FLOAT8`, `INT4`, `FLOAT4`, ...
     * @since 3.0
     */
    var sortOrder: Int = -1
        // Validated in the companion `init` block above; the setter must not call iterate() (re-entrant during init).
        private set
}
