@file:Suppress("OPT_IN_USAGE")

package naksha.model.objects

import kotlin.js.JsExport
import kotlin.js.JsStatic
import kotlin.jvm.JvmField

// TODO: We need immutability for the standard members and other pre-declared members.
//       If not, we could encounter a situation where someone accidentally modified a standard member.

/**
 * The canonical set of standard members that every Naksha storage understands.
  * @since 3.0
 */
@JsExport
class StandardMembers private constructor() {

    companion object StandardMembers_C {

        // -------------------------------------------------------------------------
        // Mandatory members — storage-managed, always present.
        // -------------------------------------------------------------------------

        /**
         * `_tn` — **Tuple-Number**. The [naksha.model.TupleNumber] of this feature. This persists out of:
         * - `database-number: long` - The database in which the feature is stored.
         * - `catalog-number: int` - The catalog in which the feature is stored.
         * - `collection-number: int` - The collection in which the feature is stored.
         * - `feature-number: long` - The unique identifier of the feature within the collection.
         * - `version: long` - The version of this feature state.
         *
         * **Beware**: Not all storages will persist the full tuple-number, i.e. `lib-psql` will only store the `feature-number` as `_fn` and the `version` as `_version`, because the other parts can be deducted from the table location. Searching for parts of the tuple-number is supported by the [ReadFeatures][naksha.model.request.ReadFeatures] request using the [version][naksha.model.request.ReadFeatures.version] property.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Tn = TupleNumberMember("_tn", JsonPath("tn")).withMandatory()

        /**
         * Virtual member that refers to the feature-number of the [tuple-number][Tn], the only purpose is for queries and result ordering.
         * @since 3.0
         */
        @JvmField @JsStatic
        val FeatureNumber = Int64Member("_fn", null).withMandatory().withVirtual()

        /**
         * Virtual member that refers to the version of the [tuple-number][Tn], the only purpose is for queries and result ordering.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Version = Int64Member("_version", null).withMandatory().withVirtual()

        /**
         * Virtual, query-only member for the [action][naksha.model.Action] (the lower two bits of the
         * version); resolved to `(version & 3)` by the storage, not stored as a column.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Action = Int32Member("_action", null).withMandatory().withVirtual()

        /**
         * `_nv` — **next-version** (`INT64`). The version at which this tuple was superseded by the next state. Present only in _HISTORY_; in _HEAD_ the value is intrinsically the current [HEAD version][naksha.model.Version.HEAD].
         * @since 3.0
         */
        @JvmField @JsStatic
        val NextVersion = Int64Member("_nv", JsonPath("nv")).withMandatory()

         /**
         * `_global_book_fn` — **Global-book-feature-number** (`INT64`). References the feature-number in `naksha~books`, which carries the JBON2 global dictionary needed to decode this tuple's [Feature] blob when global-book encoding is used.
         * @since 3.0
         */
        @JvmField @JsStatic
        val GlobalBookFeatureNumber = Int64Member("_global_book_fn", JsonPath("gbfn")).withMandatory()

        /**
         * `_id` — custom feature string identifier. Either stringified feature-number _(as positive decimal number, i.e. `12345678`)_ or the unique identifier of the feature, resulting in a negative feature-number, generated by hashing the `id`. Technically, the storage can store `null`, when the feature-number is positive.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Id = StringMember("_id", JsonPath("id")).withMandatory()

        /**
         * `_feature` — **Serialised feature** (`BYTE_ARRAY`).
         * @since 3.0
         */
        @JvmField @JsStatic
        val Feature = ByteArrayMember("_feature", JsonPath()).withMandatory()

        /**
         * All mandatory members, in declaration order.
         *
         * These are always managed and persisted by the storage regardless of what is declared in
         * [NakshaCollection.members]. No implementation-specific member may be declared with the
         * same name and a different [MemberType].
         * @since 3.0
         */
        @JvmField @JsStatic
        val MANDATORY: List<Member> = listOf(Tn, NextVersion, Feature, Id, GlobalBookFeatureNumber)

        // -------------------------------------------------------------------------
        // Optional members.
        // -------------------------------------------------------------------------

        /**
         * `pn` — **Publish-number** (`INT64`). A sequencer-assigned, gap-free sequential number
         * ordered by **visibility** rather than execution order. Unlike `version`, which can have
         * holes (rolled-back transactions) and allows concurrent transactions to commit out of
         * order (e.g. version 3 commits before version 2), the publish-number is a strict
         * monotonically increasing sequence with no gaps: after `5` comes `6`, guaranteed.
         *
         * This is important for change-event subscribers that need a reliable, ordered cursor
         * into the transaction stream. The publish-number is `null` until the publisher
         * (an external sequencer component) has processed the transaction.
         *
         * Currently used only in `naksha~transactions`.
         * @since 3.0
         */
        @JvmField @JsStatic
        val PublishNumber = Int64Member("pn")

        /**
         * `pt` — **Publish-time** (`INT64`). The millisecond epoch timestamp at which the
         * publisher recognised and sequenced the transaction, assigning it its [PublishNumber].
         * `null` until the publisher has processed the transaction.
         *
         * Currently used only in `naksha~transactions`.
         * @since 3.0
         */
        @JvmField @JsStatic
        val PublishTime = Int64Member("pt")

        /**
         * `gv` — **Global-version** (`INT64`). The HERE-internal global version number,
         * assigned by HERE's global sequencing infrastructure. `null` until the global
         * sequencer has processed the transaction.
         *
         * Currently used only in `naksha~transactions`.
         * @since 3.0
         */
        @JvmField @JsStatic
        val GlobalVersion = Int64Member("gv")

        /**
         * `geo` — feature geometry stored as TWKB. `null` if the feature has no geometry.
         * Default member.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Geometry = SpatialMember("geo", JsonPath("geometry"))

        /**
         * `cc` — change-count: how many times this feature has been modified. There is some special low-level treatment for this member, if it is added to a collection. It is always initialized with `1` and incremented for every new state.
         * @since 3.0
         */
        @JvmField @JsStatic
        val ChangeCount = Int32Member("cc", JsonPath("properties", "changeCount"))
     }
}
