@file:Suppress("OPT_IN_USAGE")

package naksha.model.objects

import kotlin.js.JsExport
import kotlin.js.JsStatic
import kotlin.jvm.JvmField

/**
 * The canonical set of standard members that every Naksha storage understands.
  * @since 3.0
 */
@JsExport
class StandardMembers private constructor() {

    companion object StandardMembers_C {

        // -------------------------------------------------------------------------
        // Mandatory members — storage-managed, always present.
        // -------------------------------------------------------------------------

        /**
         * `tn` — **Tuple-Number**. The [naksha.model.TupleNumber] of this feature. This persists out of:
         * - `database-number: long` - The database in which the feature is stored.
         * - `catalog-number: int` - The catalog in which the feature is stored.
         * - `collection-number: int` - The collection in which the feature is stored.
         * - `feature-number: long` - The unique identifier of the feature within the collection.
         * - `version: long` - The version of this feature state.
         *
         * Note all storages will persist the tuple-number like this, i.e. `lib-psql` will only store the `feature-number` as `fn` and the `version`. The other parts can be deducted from the storage location.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Tn = Member("~tn", MemberType.TUPLE_NUMBER, JsonPath("tn"))

         /**
         * `nv` — **next-version** (`INT64`). The version at which this tuple was superseded
         * by the next state. Present only in history; in head the value is intrinsically the current
         * HEAD sentinel and is not stored as a physical member. Mandatory, storage-managed.
         * @since 3.0
         */
        @JvmField @JsStatic
        val NextVersion = Member("~nv", MemberType.INT64, JsonPath("nv"))

         /**
         * `gbn` — **Global-book-number** (`INT64`). References the `global_book_fn` in
         * `naksha~books`, which carries the JBON2 global dictionary needed to decode this tuple's
         * [Feature] blob when global-book encoding is used. Assigned by the sequencer; `null` when
         * no global book is in use. Mandatory, storage-managed (but physically `null` until the
         * sequencer populates it).
         *
         * A conditional non-unique index on this member is always created so that the sequencer can
         * efficiently locate all tuples that reference a particular book.
         * @since 3.0
         */
        @JvmField @JsStatic
        val GlobalBookFeatureNumber = Member("~gbn", MemberType.INT64, JsonPath("gbn"))

        /**
         * `feature` — **Serialised feature** (`BYTE_ARRAY`). The encoded feature blob. The encoding is controlled by [NakshaCollection.dataEncoding]. Mandatory, storage-managed. The feature member is special in that it represents the feature itself, therefore the path is an empty list!
         * @since 3.0
         */
        @JvmField @JsStatic
        val Feature = Member("~feature", MemberType.BYTE_ARRAY, JsonPath())

        /**
         * `id` — feature string identifier. Either stringified `feature-number` _(as positive decimal number, i.e. `12345678`)_ or the unique identifier of the feature, resulting in a negative `feature-number`, generated by hashing the `id`. Technically, the storage can store `null`, when the `feature-number` is positive.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Id = Member("~id", MemberType.STRING, JsonPath("id"))

        /**
         * All mandatory members, in declaration order.
         *
         * These are always managed and persisted by the storage regardless of what is declared in
         * [NakshaCollection.members]. No implementation-specific member may be declared with the
         * same name and a different [MemberType].
         * @since 3.0
         */
        @JvmField @JsStatic
        val MANDATORY: List<Member> = listOf(Tn, NextVersion, Feature, Id, GlobalBookFeatureNumber)

        // -------------------------------------------------------------------------
        // Optional members.
        // -------------------------------------------------------------------------

        /**
         * `pn` — **Publish-number** (`INT64`). A sequencer-assigned, gap-free sequential number
         * ordered by **visibility** rather than execution order. Unlike `version`, which can have
         * holes (rolled-back transactions) and allows concurrent transactions to commit out of
         * order (e.g. version 3 commits before version 2), the publish-number is a strict
         * monotonically increasing sequence with no gaps: after `5` comes `6`, guaranteed.
         *
         * This is important for change-event subscribers that need a reliable, ordered cursor
         * into the transaction stream. The publish-number is `null` until the publisher
         * (an external sequencer component) has processed the transaction.
         *
         * Currently used only in `naksha~transactions`.
         * @since 3.0
         */
        @JvmField @JsStatic
        val PublishNumber = Member("pn", MemberType.INT64)

        /**
         * `pt` — **Publish-time** (`INT64`). The millisecond epoch timestamp at which the
         * publisher recognised and sequenced the transaction, assigning it its [PublishNumber].
         * `null` until the publisher has processed the transaction.
         *
         * Currently used only in `naksha~transactions`.
         * @since 3.0
         */
        @JvmField @JsStatic
        val PublishTime = Member("pt", MemberType.INT64)

        /**
         * `gv` — **Global-version** (`INT64`). The HERE-internal global version number,
         * assigned by HERE's global sequencing infrastructure. `null` until the global
         * sequencer has processed the transaction.
         *
         * Currently used only in `naksha~transactions`.
         * @since 3.0
         */
        @JvmField @JsStatic
        val GlobalVersion = Member("gv", MemberType.INT64)

        /**
         * `geo` — feature geometry stored as TWKB. `null` if the feature has no geometry.
         * Default member.
         * @since 3.0
         */
        @JvmField @JsStatic
        val Geometry = Member("geo", MemberType.SPATIAL, JsonPath("geometry"))
     }
}
