import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.shadow)
}

description = gatherDescription()
version = "0.1.0"
val mainCliClass = "com.here.naksha.cli.Main"
val fatJarBaseName = "naksha-cli"
val versionFile = project.projectDir.resolve("src/jvmMain/java/com/here/naksha/cli/VersionInfo.java")

configurations.all {
    exclude(group = "org.slf4j", module = "slf4j-simple")
}

kotlin {
    jvmToolchain(23)

    jvm {
        mainRun {
            mainClass.set(mainCliClass)
        }
    }

    sourceSets {
        jvmMain {
            dependencies {
                implementation(libs.picocli)
                implementation(libs.bundles.logging)
                implementation(project(":here-naksha-lib-base"))
                implementation(project(":here-naksha-lib-model"))
                implementation(project(":here-naksha-lib-psql"))
                implementation(project(":here-naksha-lib-core"))
            }
        }
        jvmTest {
            dependencies {
                implementation(libs.bundles.testing)
                implementation(libs.test.containers)
            }
        }
    }
}

tasks {
    getByName<Jar>("jvmJar") { dependsOn("jvmProcessResources") }
    getByName<ProcessResources>("jvmTestProcessResources") { dependsOn("jvmProcessResources") }
    getByName<Test>("jvmTest") {
        useJUnitPlatform()
        maxHeapSize = "6g"
    }

    val shadowCreate by registering(ShadowJar::class) {
        group = "Shadow"
        description = "Creates fat jar"
        archiveBaseName.set(fatJarBaseName)
        archiveClassifier.set("")
        archiveVersion.set(version.toString())
        manifest {
            attributes["Main-Class"] = mainCliClass
        }
        from(kotlin.jvm().compilations.getByName("main").output)
        configurations = listOf(project.configurations.getByName("jvmRuntimeClasspath"))
    }

    val generateVersionFile by registering {
        doLast {
            if (!versionFile.exists()) throw GradleException("${versionFile.name} file not found: ${versionFile.path}")
            versionFile.writeText(
                """
            package com.here.naksha.cli;
            import picocli.CommandLine;
            // This file is auto-generated by Gradle. ANY CHANGE WILL BE OVERWRITTEN!
            public final class VersionInfo implements CommandLine.IVersionProvider {
                @Override
                public String[] getVersion() {
                    return new String[] {"$fatJarBaseName $version"};
                }
                private VersionInfo() {}
            }
            """.trimIndent()
            )
        }
    }

    getByName("jvmMainClasses") {
        dependsOn(generateVersionFile)
    }
}

setOverallCoverage(0.0) // only increasing allowed!