package com.here.naksha.lib.core.models.naksha;

import naksha.base.AnyObject;
import naksha.base.JsEnum;
import naksha.base.JvmPropertyUtil;
import naksha.base.NullableProperty;
import naksha.base.Platform;
import naksha.model.objects.JsonPath;
import naksha.model.objects.MemberType;
import org.jetbrains.annotations.Nullable;

/** A typed property to materialize and, except for booleans, index. Names are generated by the compiler. */
public final class CustomIndexMapping extends AnyObject {
  private static final NullableProperty<CustomIndexMapping, JsonPath> JSON_PATH =
      JvmPropertyUtil.nullableProperty(JsonPath.class, "jsonPath");

  public CustomIndexMapping() {}

  public CustomIndexMapping(JsonPath jsonPath, MemberType dataType) {
    setJsonPath(jsonPath);
    setDataType(dataType);
  }

  public @Nullable JsonPath getJsonPath() {
    return JSON_PATH.getValue(this);
  }

  public void setJsonPath(@Nullable JsonPath jsonPath) {
    JSON_PATH.setValue(this, jsonPath);
  }

  public @Nullable MemberType getDataType() {
    return JsEnum.getDefined(getRaw("dataType"), Platform.klassFor(MemberType.class));
  }

  public void setDataType(@Nullable MemberType dataType) {
    setRaw("dataType", dataType == null ? null : dataType.getValue());
  }
}
