name: CI-Only Workflow

# Trigger for commit on any branch, other than the ones in the list
on:
  push:
    branches-ignore:
      - master
      - int
      - develop
      - Naksha_maintenance
      - MCPODS-6260_dev_deployment
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ### Job to Build and Publish artifacts
  Build-and-Publish:
    uses: ./.github/workflows/reusable-build-and-publish.yml
