name: CI-Only Workflow

# Trigger for specified criteria (specifically for PRs against stable branches)
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - int
      - develop
      - Naksha_maintenance
      - MCPODS-6260_dev_deployment

jobs:
  ### Job to Build and Publish artifacts
  Build-and-Publish:
    uses: ./.github/workflows/reusable-build-and-publish.yml
