on:
  # Input - aws_key, aws_secret, aws_region, github artifact name, s3 bucket name
  # Output - S3 bucket artifact path (e.g. 1.1.1/deployment.tar.gz)
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      github-artifact-name:
        required: true
        type: string
      s3-bucket-name:
        required: true
        type: string
    secrets:
      aws-key:
        required: true
        type: string
      aws-secret:
        required: true
        type: string

jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch CodeDeploy artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.github-artifact-name }}
      - name: List CodeDeploy artifacts
        run: |
          ls -lR .
      - run: echo "🍏 This job's status is ${{ job.status }}."
