on:
  # Input - aws_key, aws_secret, aws_region, github artifact name, s3 bucket name
  # Output - S3 bucket artifact path (e.g. 1.1.1/deployment.tar.gz)
  workflow_call:
    inputs:
      aws-region:
        type: string
        description: 'AWS region the S3 bucket is associated with'
        required: true
      github-artifact-name:
        type: string
        description: 'Github pipeline artifact name, which can be downloaded using actions/download-artifact'
        required: true
      s3-bucket-name:
        type: string
        description: 'AWS S3 bucket name, where artifact is to be released to'
        required: true
      s3-bucket-dir-path:
        type: string
        description: 'AWS S3 bucket directory path, where artifact is to be uploaded into'
        required: true
      s3-artifact-version:
        type: string
        description: 'A version (or suffix) to be used in artifact name while uploading it to AWS S3 bucket'
        required: true
    secrets:
      aws-key:
        description: 'AWS Access key of a user, who is allowed to upload artifact to S3 bucket'
        required: true
      aws-secret:
        description: 'AWS Access secret of a user, who is allowed to upload artifact to S3 bucket'
        required: true

jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch CodeDeploy artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.github-artifact-name }}
      - name: List CodeDeploy artifacts
        run: |
          ls -lR .
      - name: Preparing S3 artifact name
        id: s3-artifact-name
        run: |
          BUNDLE_NAME=deployment_${{ inputs.s3-artifact-version }}.tar.gz
          echo "name=$BUNDLE_NAME" >> "$GITHUB_OUTPUT"
      - name: Preparing S3 artifact bundle
        run: |
          tar -cvzf $BUNDLE_NAME .
          ls -lR .
        env:
          BUNDLE_NAME: ${{ steps.s3-artifact-name.outputs.name }}
      - name: Preparing full S3 bucket path
        run: |
          echo "s3://${{ inputs.s3-bucket-name }}/${{ inputs.s3-bucket-dir-path }}/$BUNDLE_NAME"
        env:
          BUNDLE_NAME: ${{ steps.s3-artifact-name.outputs.name }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
